package report

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/ghchinoy/montage/internal/model"
)

// RenderJSON serializes the assessment report to formatted JSON bytes.
func RenderJSON(r *model.AssessmentReport) ([]byte, error) {
	return json.MarshalIndent(r, "", "  ")
}

// RenderMarkdown creates a rich Markdown assessment report.
func RenderMarkdown(r *model.AssessmentReport) string {
	var b strings.Builder

	targetName := r.Target.Name
	if targetName == "" {
		targetName = "Target Application"
	}

	b.WriteString(fmt.Sprintf("# 🗺️ Montage Agent Readiness Assessment: `%s`\n\n", targetName))
	b.WriteString(fmt.Sprintf("> Generated by **Montage** on %s\n\n", r.GeneratedAt.Format(time.RFC1123)))

	// Executive Summary Cards
	b.WriteString("## 📊 Executive Summary\n\n")
	b.WriteString(fmt.Sprintf("- **Readiness Score:** `%d / 100`\n", r.OverallScore))
	b.WriteString(fmt.Sprintf("- **Readiness Tier:** **%s**\n", r.Tier))
	if r.Target.URL != "" {
		b.WriteString(fmt.Sprintf("- **Repository:** [%s](%s)\n", r.Target.URL, r.Target.URL))
	} else {
		b.WriteString(fmt.Sprintf("- **Local Path:** `%s`\n", r.Target.LocalPath))
	}
	if r.Target.PrimaryLang != "" {
		b.WriteString(fmt.Sprintf("- **Primary Language:** `%s`\n", r.Target.PrimaryLang))
	}
	if r.Target.Description != "" {
		b.WriteString(fmt.Sprintf("- **Description:** *%s*\n", r.Target.Description))
	}
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("> **Tier Assessment:** %s\n\n", r.TierSummary))

	// Dimension Breakdown Table
	b.WriteString("### 🎯 Dimensional Scorecard\n\n")
	b.WriteString("| Dimension | Weight | Score | Status | Key Observation |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, dim := range r.Dimensions {
		status := "🟢 Ready"
		if dim.Score < 50 {
			status = "🔴 Action Needed"
		} else if dim.Score < 75 {
			status = "🟡 Moderate"
		}

		keyObs := "No major issues"
		if len(dim.Strengths) > 0 {
			keyObs = dim.Strengths[0]
		} else if len(dim.Gaps) > 0 {
			keyObs = dim.Gaps[0]
		}

		b.WriteString(fmt.Sprintf("| **%s** | %.0f%% | `%d / 100` | %s | %s |\n",
			dim.Name, dim.Weight*100, dim.Score, status, keyObs))
	}
	b.WriteString("\n---\n\n")

	// Capabilities Assessment & Ecosystem Grouping Table
	if len(r.Capabilities) > 0 {
		b.WriteString("## 🧭 Capabilities Assessment & Agent Ecosystem Grouping\n\n")
		b.WriteString("Rather than treating the application as a single monolithic tool, Montage decomposes it into discrete capabilities and maps each to its optimal agent target:\n\n")
		b.WriteString("| Capability | Source / Ref | Nature | Target Artifact | Grouping / Domain | Architectural Rationale |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for _, c := range r.Capabilities {
			targetIcon := "🔌 MCP Tool"
			switch c.RecommendedTarget {
			case model.TargetPureSkill:
				targetIcon = "📝 Pure Skill"
			case model.TargetSkillWithCode:
				targetIcon = "⚡ Skill with Code"
			case model.TargetCLICommand:
				targetIcon = "💻 CLI Tool"
			case model.TargetMCPTool:
				targetIcon = "🔌 MCP Tool"
			}
			access := "🔒 Read-Only"
			if c.IsMutating {
				access = "⚡ Mutating"
			}
			b.WriteString(fmt.Sprintf("| **%s** | `%s` | %s | **%s** | `%s` | %s |\n",
				c.Name, c.SourceRef, access, targetIcon, c.TargetGrouping, c.Rationale))
		}
		b.WriteString("\n---\n\n")
	}

	// Specialized Multi-Skill Blueprints
	if len(r.SkillBlueprints) > 0 {
		b.WriteString("## 📚 Specialized Skill Blueprints\n\n")
		b.WriteString("Montage synthesized the following domain-specific skills for your agent environment:\n\n")
		for i, sb := range r.SkillBlueprints {
			kindBadge := "📝 PURE SKILL"
			if sb.Kind == "skill_with_code" {
				kindBadge = "⚡ SKILL WITH CODE"
			}
			b.WriteString(fmt.Sprintf("### %d. `%s` (%s)\n", i+1, sb.Name, kindBadge))
			b.WriteString(fmt.Sprintf("- **Domain:** `%s`\n", sb.Domain))
			b.WriteString(fmt.Sprintf("- **Description:** %s\n", sb.Description))
			if sb.HelperScript != "" {
				b.WriteString(fmt.Sprintf("- **Bundled Script:** `%s` (%s)\n", sb.HelperScript, sb.TokenSavingsEst))
			}
			b.WriteString("- **Encompassed Capabilities:**\n")
			for _, capName := range sb.Capabilities {
				b.WriteString(fmt.Sprintf("  - %s\n", capName))
			}
			b.WriteString("- **Workflow Guidelines:**\n")
			for _, inst := range sb.KeyInstructions {
				b.WriteString(fmt.Sprintf("  - %s\n", inst))
			}
			b.WriteString("\n")
		}
		b.WriteString("---\n\n")
	}

	// Clustered MCP Toolsets
	if len(r.ToolGroups) > 0 {
		b.WriteString("## 🔌 Clustered MCP Toolsets\n\n")
		b.WriteString("To avoid bloated toolsets, MCP tools are grouped by operational persona:\n\n")
		for _, grp := range r.ToolGroups {
			b.WriteString(fmt.Sprintf("### Group: `%s`\n", grp.Name))
			b.WriteString(fmt.Sprintf("*%s*\n\n", grp.Description))
			b.WriteString("| Tool Name | Access | Description |\n")
			b.WriteString("|---|---|---|\n")
			for _, t := range grp.Tools {
				access := "🔒 Read-Only"
				if !t.IsReadOnly {
					access = "⚡ Mutating"
				}
				b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n", t.Name, access, t.Description))
			}
			b.WriteString("\n")
		}
		b.WriteString("---\n\n")
	}

	// The Agent Ecosystem Spectrum
	b.WriteString("## 🧩 Full Agent Ecosystem Blueprint\n\n")
	b.WriteString("Montage evaluates what Agent Ecosystem tooling can be generated from this codebase across the four tiers of the agent artifact spectrum:\n\n")

	// 1. Pure Skill
	b.WriteString(fmt.Sprintf("### 1. Pure Skill (`%s`)\n", r.PureSkill.SuggestedName))
	b.WriteString(fmt.Sprintf("- **Feasibility:** `%s` (Score: %d/100)\n", r.PureSkill.Feasibility, r.PureSkill.Score))
	b.WriteString(fmt.Sprintf("- **Purpose:** %s\n", r.PureSkill.Description))
	b.WriteString("- **Recommended Use Cases:**\n")
	for _, use := range r.PureSkill.RecommendedUses {
		b.WriteString(fmt.Sprintf("  - %s\n", use))
	}
	b.WriteString("- **Key Workflow Rules:**\n")
	for _, rule := range r.PureSkill.KeyInstructions {
		b.WriteString(fmt.Sprintf("  - %s\n", rule))
	}
	b.WriteString("\n")

	// 2. Skill with Code
	b.WriteString(fmt.Sprintf("### 2. Skill with Code (`%s`)\n", r.SkillWithCode.SuggestedName))
	b.WriteString(fmt.Sprintf("- **Feasibility:** `%s` (Score: %d/100)\n", r.SkillWithCode.Feasibility, r.SkillWithCode.Score))
	b.WriteString(fmt.Sprintf("- **Token Savings Estimate:** `%s`\n", r.SkillWithCode.TokenSavingsEst))
	b.WriteString("- **Bundled Executable / Script:**\n")
	for _, script := range r.SkillWithCode.HelperScripts {
		b.WriteString(fmt.Sprintf("  - `%s`\n", script))
	}
	b.WriteString("- **Execution Flow:**\n")
	for _, step := range r.SkillWithCode.RecommendedFlow {
		b.WriteString(fmt.Sprintf("  1. %s\n", step))
	}
	b.WriteString("\n")

	// 3. MCP Server
	b.WriteString(fmt.Sprintf("### 3. Model Context Protocol (MCP) Server (`%s`)\n", r.MCPServer.ServerName))
	b.WriteString(fmt.Sprintf("- **Feasibility:** `%s` (Score: %d/100)\n", r.MCPServer.Feasibility, r.MCPServer.Score))
	b.WriteString(fmt.Sprintf("- **Transport:** `%s`\n", r.MCPServer.Transport))
	b.WriteString("- **Candidate MCP Tools:**\n\n")
	b.WriteString("| Tool Name | Access | Description | CLI Source |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, t := range r.MCPServer.ProposedTools {
		access := "🔒 Read-Only"
		if !t.IsReadOnly {
			access = "⚡ Mutating"
		}
		source := t.SourceCmd
		if source == "" {
			source = "n/a"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | `%s` |\n", t.Name, access, t.Description, source))
	}
	b.WriteString("\n")

	if len(r.MCPServer.ProposedResources) > 0 {
		b.WriteString("- **Proposed MCP Resources:**\n")
		for _, res := range r.MCPServer.ProposedResources {
			b.WriteString(fmt.Sprintf("  - `%s`\n", res))
		}
		b.WriteString("\n")
	}

	// 4. Agent Plugin
	b.WriteString(fmt.Sprintf("### 4. Agent Plugin (`%s`)\n", r.AgentPlugin.PluginName))
	b.WriteString(fmt.Sprintf("- **Feasibility:** `%s` (Score: %d/100)\n", r.AgentPlugin.Feasibility, r.AgentPlugin.Score))
	b.WriteString(fmt.Sprintf("- **Description:** %s\n", r.AgentPlugin.Description))
	b.WriteString("- **Plugin Artifacts:**\n")
	for _, comp := range r.AgentPlugin.Components {
		b.WriteString(fmt.Sprintf("  - `%s`\n", comp))
	}
	b.WriteString("\n---\n\n")

	// Actionable Gaps & Modernization Roadmap
	b.WriteString("## 🛠️ Actionable Gaps & Modernization Roadmap\n\n")
	if len(r.ActionableGaps) == 0 {
		b.WriteString("✅ **Zero critical gaps detected!** This application is highly optimized for autonomous agent interaction.\n\n")
	} else {
		for i, gap := range r.ActionableGaps {
			badge := "🟡 MEDIUM"
			if gap.Priority == "High" {
				badge = "🔴 HIGH PRIORITY"
			} else if gap.Priority == "Low" {
				badge = "🟢 LOW PRIORITY"
			}

			b.WriteString(fmt.Sprintf("### %d. [%s] %s (%s)\n", i+1, badge, gap.Title, gap.Dimension))
			b.WriteString(fmt.Sprintf("%s\n\n", gap.Description))
			b.WriteString(fmt.Sprintf("**Remediation:** %s\n\n", gap.Remediation))
			if gap.ExampleCode != "" {
				b.WriteString("```go\n")
				b.WriteString(gap.ExampleCode)
				b.WriteString("\n```\n\n")
			}
		}
	}

	b.WriteString("---\n\n")

	// Sample Client Configuration Snippet
	b.WriteString("## ⚙️ Quickstart MCP Configuration\n\n")
	b.WriteString("Add this to your MCP client config (`claude_desktop_config.json` or `opencode.json`):\n\n")
	b.WriteString("```json\n")
	b.WriteString("{\n")
	b.WriteString("  \"mcpServers\": {\n")
	b.WriteString(fmt.Sprintf("    \"%s\": {\n", strings.ToLower(targetName)))
	b.WriteString(fmt.Sprintf("      \"command\": \"%s\",\n", strings.ToLower(targetName)))
	b.WriteString("      \"args\": [\"mcp\"]\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("```\n")

	return b.String()
}
